In [1]:
import numpy as np 
a = np.array([1,2,3])  
print (a)

[1 2 3]


In [2]:
a = np.array([[1,2],[3,4]])

In [3]:
a

array([[1, 2],
       [3, 4]])

In [4]:
# 最小维度  
a = np.array([1,2,3,4,5],ndmin=2)

In [5]:
a

array([[1, 2, 3, 4, 5]])

In [6]:
# 使用标量类型
dt = np.dtype(np.int32)
print(dt)

int32


In [7]:
# int8, int16, int32, int64 四种数据类型可以使用字符串 'i1', 'i2','i4','i8' 代替
dt = np.dtype('i4')
print(dt)

int32


In [8]:
dt = np.dtype([('age',np.int8)]) 
print(dt)

[('age', 'i1')]


In [9]:
dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print(a)

[(10,) (20,) (30,)]


In [10]:
# 类型字段名可以用于存取实际的 age 列
import numpy as np
dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print(a['age'])

[10 20 30]


In [11]:
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
print(student)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]


In [12]:
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
print(a)

[(b'abc', 21, 50.) (b'xyz', 18, 75.)]


NumPy 数组的维数称为秩（rank），一维数组的秩为 1，二维数组的秩为 2，以此类推。

在 NumPy中，每一个线性的数组称为是一个轴（axis），也就是维度（dimensions）。比如说，二维数组相当于是两个一维数组，其中第一个一维数组中每个元素又是一个一维数组。所以一维数组就是 NumPy 中的轴（axis），第一个轴相当于是底层数组，第二个轴是底层数组里的数组。而轴的数量——秩，就是数组的维数。

很多时候可以声明 axis。axis=0，表示沿着第 0 轴进行操作，即对每一列进行操作；axis=1，表示沿着第1轴进行操作，即对每一行进行操作。

ndarray.ndim	秩，即轴的数量或维度的数量
ndarray.shape	数组的维度，对于矩阵，n 行 m 列
ndarray.size	数组元素的总个数，相当于 .shape 中 n*m 的值
ndarray.dtype	ndarray 对象的元素类型
ndarray.itemsize	ndarray 对象中每个元素的大小，以字节为单位
ndarray.flags	ndarray 对象的内存信息
ndarray.real	ndarray元素的实部
ndarray.imag	ndarray 元素的虚部
ndarray.data	包含实际数组元素的缓冲区，由于一般通过数组的索引获取元素，所以通常不需要使用这个属性

In [13]:
a = np.arange(24)  
print (a.ndim)             # a 现只有一个维度
# 现在调整其大小
b = a.reshape(2,4,3)  # b 现在拥有三个维度
print (b.ndim)

1
3


In [14]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [17]:
c = a.reshape(1,8,3)

In [18]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [19]:
a.ndim

1

In [20]:
c.ndim

3

In [21]:
np.array([1,2]).ndim

1

In [22]:
np.array([[1,2]]).ndim

2

In [23]:
# ndarray.itemsize
# ndarray.itemsize 以字节的形式返回数组中每一个元素的大小。

In [24]:
# 数组的 dtype 为 int8（一个字节）  
x = np.array([1,2,3,4,5], dtype = np.int8)  
print (x.itemsize)
 
# 数组的 dtype 现在为 float64（八个字节） 
y = np.array([1,2,3,4,5], dtype = np.float64)  
print (y.itemsize)

1
8


In [25]:
# 默认为浮点数
x = np.zeros(5) 
print(x)
 
# 设置类型为整数
y = np.zeros((5,), dtype = np.int) 
print(y)
 
# 自定义类型
z = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print(z)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [26]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [27]:
np.ones([2,3],dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [29]:
# 创建 randn(size) 服从 X~N(0,1) 的正态分布随机数组
from numpy import *
a=random.randn(2,3)
print(a)

[[-0.17655857  0.43638096  0.8114866 ]
 [ 0.20907341 -0.71366687  1.69501347]]


In [30]:
a.ndim

2

In [31]:
x =  [1,2,3] 
a = np.asarray(x)  
print (a)

[1 2 3]


In [32]:
type(a)

numpy.ndarray

In [33]:
x =  (1,2,3) 
a = np.asarray(x)  
print (a)


[1 2 3]


In [34]:
x =  [1,2,3] 
a = np.asarray(x, dtype =  float)  
print (a)

[1. 2. 3.]


In [35]:
s =  b'Hello World' 
a = np.frombuffer(s, dtype =  'S1')  
print (a)


[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


In [36]:
x = np.arange(10,20,2)  
print (x)

[10 12 14 16 18]


In [37]:
a = np.linspace(1,10,10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [38]:
type(a)

numpy.ndarray

In [39]:
np.logspace(1.0,2.0 ,num =10)

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

In [40]:
#上面的默认底数是10

In [41]:
np.logspace(0,9,10,base=2)

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [42]:
a = linspace(0,2*pi,21)

In [43]:
a

array([0.        , 0.31415927, 0.62831853, 0.9424778 , 1.25663706,
       1.57079633, 1.88495559, 2.19911486, 2.51327412, 2.82743339,
       3.14159265, 3.45575192, 3.76991118, 4.08407045, 4.39822972,
       4.71238898, 5.02654825, 5.34070751, 5.65486678, 5.96902604,
       6.28318531])

In [44]:
b= sin(a)

In [45]:
b

array([ 0.00000000e+00,  3.09016994e-01,  5.87785252e-01,  8.09016994e-01,
        9.51056516e-01,  1.00000000e+00,  9.51056516e-01,  8.09016994e-01,
        5.87785252e-01,  3.09016994e-01,  1.22464680e-16, -3.09016994e-01,
       -5.87785252e-01, -8.09016994e-01, -9.51056516e-01, -1.00000000e+00,
       -9.51056516e-01, -8.09016994e-01, -5.87785252e-01, -3.09016994e-01,
       -2.44929360e-16])

In [52]:
import matplotlib as plt

In [50]:
plot(a,b)

TypeError: 'module' object is not callable