In [2]:
from numpy import *

In [3]:
lst = [0,1,2,3]

In [4]:
a = array(lst)

In [5]:
a

array([0, 1, 2, 3])

In [6]:
type(a)

numpy.ndarray

In [7]:
a.dtype

dtype('int64')

In [8]:
a.itemsize

8

In [9]:
a.nbytes

32

In [10]:
#使用fill方法设定初始值

In [11]:
a.fill(-4.8)

In [12]:
a

array([-4, -4, -4, -4])

In [13]:
a = array([0,1,2,3])

In [14]:
a

array([0, 1, 2, 3])

In [15]:
a[0]

0

In [16]:
a[0] = 10

In [17]:
a

array([10,  1,  2,  3])

In [18]:
a= array([11,12,13,14,15])

In [19]:
a[1:3]

array([12, 13])

In [20]:
a[1:-2]

array([12, 13])

In [21]:
a[-4:3]

array([12, 13])

In [24]:
a[-5:-3]

array([11, 12])

In [25]:
a[::2]

array([11, 13, 15])

In [27]:
od = array([21000, 21180, 21240, 22100, 22400])
dist = od[1:] - od[:-1]

In [28]:
dist

array([180,  60, 860, 300])

In [29]:
od[1:]

array([21180, 21240, 22100, 22400])

In [30]:
od[:-1]

array([21000, 21180, 21240, 22100])

In [31]:
a = array([[ 0, 1, 2, 3],
           [10,11,12,13]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [32]:
#多维数组切片

In [33]:
a = array([[ 0, 1, 2, 3, 4, 5],
           [10,11,12,13,14,15],
           [20,21,22,23,24,25],
           [30,31,32,33,34,35],
           [40,41,42,43,44,45],
           [50,51,52,53,54,55]])

In [34]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [35]:
a[0,3:5]

array([3, 4])

In [36]:
a[4:,4:]

array([[44, 45],
       [54, 55]])

In [37]:
a[:,2]

array([ 2, 12, 22, 32, 42, 52])

In [38]:
a[2::2,::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [39]:
# 切片是引用机制

In [40]:
a = array([0,1,2,3,4])

In [41]:
b = a[2:4].copy()

In [42]:
b [ 0 ] = 10

In [43]:
a

array([0, 1, 2, 3, 4])

In [44]:
b

array([10,  3])

In [45]:
a = arange(0,80,10)

In [46]:
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [47]:
indices = [ 1,2,-3]

In [48]:
y = a[indices]

In [49]:
y

array([10, 20, 50])

In [50]:
mask = array([0,1,1,0,0,1,0,0],
            dtype=bool)

In [51]:
a[mask]

array([10, 20, 50])

In [52]:
#花式索引，这个骚气

In [54]:
from numpy.random import rand
a = rand(10)
a

array([0.09844009, 0.12476911, 0.23475371, 0.77256763, 0.19969085,
       0.36729473, 0.43981053, 0.37998489, 0.87720408, 0.45307798])

In [55]:
mask = a > 0.5

In [57]:
mask

array([False, False, False,  True, False, False, False, False,  True,
       False])

In [58]:
# 二维花式索引

In [59]:
a = array([[ 0, 1, 2, 3, 4, 5],
           [10,11,12,13,14,15],
           [20,21,22,23,24,25],
           [30,31,32,33,34,35],
           [40,41,42,43,44,45],
           [50,51,52,53,54,55]])
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [61]:
a[(0,1,2,3,4),(1,2,3,4,5)]

array([ 1, 12, 23, 34, 45])

In [62]:
a[3:,[0,2,5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [63]:
mask = array([1,0,1,0,0,1],
            dtype =bool)

In [64]:
a[mask,2]

array([ 2, 22, 52])

In [65]:
mask = array([True,False,True,False,False,True])

In [66]:
a[mask,2]

array([ 2, 22, 52])

In [67]:
y =a[:3]

In [68]:
y

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25]])

In [72]:
a = arange(64)
a.shape = 4,4,4
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [73]:
y = a[:,:,[2,-1]]

In [74]:
y

array([[[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]],

       [[18, 19],
        [22, 23],
        [26, 27],
        [30, 31]],

       [[34, 35],
        [38, 39],
        [42, 43],
        [46, 47]],

       [[50, 51],
        [54, 55],
        [58, 59],
        [62, 63]]])

In [75]:
a = array([0,12,5,20])

In [76]:
a > 10

array([False,  True, False,  True])

In [77]:
where(a>10)

(array([1, 3]),)

In [78]:
indices = where(a > 10)
indices = indices[0]
indices

array([1, 3])

In [79]:
indices

array([1, 3])

In [80]:
loc = where(a > 10)

In [82]:
a[loc]

array([12, 20])

In [83]:
a = array([[0, 12, 5, 20],
           [1, 2, 11, 15]])
loc = where(a > 10)

In [84]:
loc

(array([0, 0, 1, 1]), array([1, 3, 2, 3]))