In [1]:
from numpy import *

In [2]:
#复数数组

In [3]:
a = array([1+1j,2,3,4])

In [4]:
a.dtype

dtype('complex128')

In [5]:
a.real

array([1., 2., 3., 4.])

In [6]:
a.imag

array([1., 0., 0., 0.])

In [7]:
a.imag = [1,2,3,4]

In [8]:
a

array([1.+1.j, 2.+2.j, 3.+3.j, 4.+4.j])

In [9]:
a = array([0.,1,2,3])
a.dtype

dtype('float64')

In [10]:
a.imag

array([0., 0., 0., 0.])

In [11]:
a = array([0,1.0,2,3])

In [12]:
a

array([0., 1., 2., 3.])

In [13]:
a.dtype

dtype('float64')

In [14]:
type(a)

numpy.ndarray

In [15]:
a.nbytes

32

In [16]:
a = array([0,1.0,2],dtype =float32)

In [17]:
a

array([0., 1., 2.], dtype=float32)

In [18]:
a = array([1,1.2,"hello",[10,20,30]],dtype = object)

In [19]:
a

array([1, 1.2, 'hello', list([10, 20, 30])], dtype=object)

In [20]:
a = array([1,-2],dtype=float32)

In [21]:
asarray(a,dtype=float64)

array([ 1., -2.])

In [22]:
a

array([ 1., -2.], dtype=float32)

In [23]:
#asarray不会修改原来数组的值

In [24]:
b = asarray(a,dtype = float32)

In [25]:
b is a

True

In [26]:
a = array((1,2,3,4),dtype = int32)

In [27]:
a

array([1, 2, 3, 4], dtype=int32)