In [1]:
#数组排序

In [3]:
from numpy import *

In [4]:
names = array(['bob', 'sue', 'jan', 'ad'])
weights = array([20.8, 93.2, 53.4, 61.8])

In [5]:
sort(weights)

array([20.8, 53.4, 61.8, 93.2])

In [7]:
#argsort返回索引

In [8]:
ordered_indices = argsort(weights)

In [9]:
ordered_indices

array([0, 2, 3, 1])

In [10]:
weights[ordered_indices]

array([20.8, 53.4, 61.8, 93.2])

In [11]:
names[ordered_indices]

array(['bob', 'jan', 'ad', 'sue'], dtype='<U3')

In [12]:
data = array([20.8,  93.2,  53.4,  61.8])
data.argsort()

array([0, 2, 3, 1])

In [13]:
data

array([20.8, 93.2, 53.4, 61.8])

In [14]:
data.sort()

In [15]:
#二维数组排序，对于多位数组，sort方法默认沿着最后一维开始排序

In [16]:
a = array([
        [.2, .1, .5], 
        [.4, .8, .3],
        [.9, .6, .7]
    ])

In [17]:
a

array([[0.2, 0.1, 0.5],
       [0.4, 0.8, 0.3],
       [0.9, 0.6, 0.7]])

In [18]:
sort(a)

array([[0.1, 0.2, 0.5],
       [0.3, 0.4, 0.8],
       [0.6, 0.7, 0.9]])

In [19]:
sort(a,axis=0)

array([[0.2, 0.1, 0.3],
       [0.4, 0.6, 0.5],
       [0.9, 0.8, 0.7]])

In [20]:
sorted_array = linspace(0,1,5)

In [21]:
sorted_array

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [23]:
sorted_array = linspace(0,1,5)
values = array([.1,.8,.3,.12,.5,.25])
searchsorted(sorted_array,values)

array([1, 4, 2, 1, 2, 1])

In [24]:
sorted_array

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
# searchsorted 返回的值相当于保持第一个数组的排序性质不变，将第二个数组中的值插入第一个数组中的位置：

# 例如 0.1 在 [0.0, 0.25) 之间，所以插入时应当放在第一个数组的索引 1 处，故第一个返回值为  1。

In [26]:
bounds = .4,.6

In [27]:
bounds

(0.4, 0.6)

In [29]:
from numpy.random import  rand

In [30]:
data = rand(100)

In [31]:
data

array([0.73090111, 0.3066912 , 0.21370949, 0.11656923, 0.96844053,
       0.8331799 , 0.20754672, 0.14031802, 0.40627933, 0.67784429,
       0.18445581, 0.8987309 , 0.76843631, 0.04163542, 0.35610389,
       0.53261344, 0.79059478, 0.52733837, 0.51981208, 0.04719047,
       0.74419271, 0.89981474, 0.1058335 , 0.23032233, 0.87641989,
       0.70726534, 0.30280015, 0.85675356, 0.92364047, 0.79357671,
       0.76127056, 0.8941402 , 0.61636331, 0.7126891 , 0.99150767,
       0.23077522, 0.46248262, 0.50228037, 0.81131686, 0.92074518,
       0.68189904, 0.86891951, 0.0910706 , 0.916335  , 0.57784544,
       0.14407355, 0.58881359, 0.542353  , 0.38802999, 0.31765908,
       0.01907419, 0.26055918, 0.75445687, 0.16064128, 0.8511018 ,
       0.83930157, 0.86537443, 0.68257728, 0.8628763 , 0.19821173,
       0.69868982, 0.78907731, 0.10159647, 0.48493015, 0.1219266 ,
       0.61348473, 0.90029399, 0.9710291 , 0.90147459, 0.30709196,
       0.58027721, 0.05155113, 0.11661918, 0.39764161, 0.50120

In [32]:
data.sort()

In [33]:
data

array([0.01907419, 0.04163542, 0.04719047, 0.05155113, 0.08099189,
       0.0910706 , 0.10159647, 0.1058335 , 0.11656923, 0.11661918,
       0.1219266 , 0.14031802, 0.14407355, 0.16064128, 0.16585951,
       0.18445581, 0.19821173, 0.20196065, 0.20754672, 0.21370949,
       0.23032233, 0.23077522, 0.26037243, 0.26055918, 0.26665014,
       0.2673249 , 0.30280015, 0.3066912 , 0.30709196, 0.31765908,
       0.32802019, 0.35475081, 0.35610389, 0.36698778, 0.38802999,
       0.39764161, 0.40627933, 0.46248262, 0.48493015, 0.50120113,
       0.50228037, 0.50829647, 0.51981208, 0.52733837, 0.53261344,
       0.53557973, 0.53647674, 0.542353  , 0.57784544, 0.58027721,
       0.58881359, 0.59385377, 0.59945079, 0.61348473, 0.61636331,
       0.61801492, 0.62570687, 0.66214239, 0.67321716, 0.67784429,
       0.68189904, 0.68257728, 0.69868982, 0.70726534, 0.7126891 ,
       0.73090111, 0.74419271, 0.74763438, 0.75445687, 0.76127056,
       0.76843631, 0.77183677, 0.78907731, 0.79059478, 0.79357

In [34]:
low_idx,high_idx = searchsorted(data,bounds)

In [35]:
data[low_idx:high_idx]

array([0.40627933, 0.46248262, 0.48493015, 0.50120113, 0.50228037,
       0.50829647, 0.51981208, 0.52733837, 0.53261344, 0.53557973,
       0.53647674, 0.542353  , 0.57784544, 0.58027721, 0.58881359,
       0.59385377, 0.59945079])

In [ ]:
# 利用插入位置，将数组中所有在这两个值之间的值提取出来：
#  这个思想有趣