In [1]:
#数组形状

In [2]:
from numpy import *

In [3]:
a = arange(6)

In [4]:
a

array([0, 1, 2, 3, 4, 5])

In [5]:
a.shape = 2,3

In [6]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [8]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
# 使用 newaxis 增加数组维数

In [10]:
a = arange(3)

In [11]:
shape(a)

(3,)

In [12]:
y = a[newaxis,:]

In [13]:
y.shape

(1, 3)

In [14]:
a

array([0, 1, 2])

In [15]:
y

array([[0, 1, 2]])

In [16]:
y = a[:,newaxis]

In [17]:
y

array([[0],
       [1],
       [2]])

In [19]:
y.shape

(3, 1)

In [20]:
y = a[newaxis,newaxis,:]

In [21]:
y

array([[[0, 1, 2]]])

In [22]:
y.shape

(1, 1, 3)

In [23]:
# squeeze 方法去除多余的轴

In [24]:
a = arange(6)

In [25]:
a

array([0, 1, 2, 3, 4, 5])

In [26]:
b = a.squeeze()

In [27]:
b.shape

(6,)

In [28]:
a.shape(2,1,3)

TypeError: 'tuple' object is not callable

In [29]:
a = arange(6)
a.shape = (2,1,3)

In [30]:
a

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [31]:
a.ndim

3

In [32]:
b = a.squeeze()
b.shape

(2, 3)

In [33]:
#数组转zhi

In [34]:
a.transpose()

array([[[0, 3]],

       [[1, 4]],

       [[2, 5]]])

In [35]:
a

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [36]:
a.T

array([[[0, 3]],

       [[1, 4]],

       [[2, 5]]])

In [37]:
a

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [38]:
a = arange(60)

In [39]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [40]:
a.shape = 3,4,5

In [41]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [42]:
b = a.T

In [43]:
b.shape

(5, 4, 3)

In [44]:
b

array([[[ 0, 20, 40],
        [ 5, 25, 45],
        [10, 30, 50],
        [15, 35, 55]],

       [[ 1, 21, 41],
        [ 6, 26, 46],
        [11, 31, 51],
        [16, 36, 56]],

       [[ 2, 22, 42],
        [ 7, 27, 47],
        [12, 32, 52],
        [17, 37, 57]],

       [[ 3, 23, 43],
        [ 8, 28, 48],
        [13, 33, 53],
        [18, 38, 58]],

       [[ 4, 24, 44],
        [ 9, 29, 49],
        [14, 34, 54],
        [19, 39, 59]]])

In [45]:
a = arange(6)

In [46]:
a.shape = (2,3)

In [47]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [48]:
b = a.T

In [49]:
b[0,1] = 30

In [50]:
a

array([[ 0,  1,  2],
       [30,  4,  5]])

In [51]:
x = array([
        [0,1,2],
        [10,11,12]
    ])
y = array([
        [50,51,52],
        [60,61,62]
    ])

In [52]:
x

array([[ 0,  1,  2],
       [10, 11, 12]])

In [53]:
y

array([[50, 51, 52],
       [60, 61, 62]])

In [54]:
z = concatenate((x,y))

In [55]:
z

array([[ 0,  1,  2],
       [10, 11, 12],
       [50, 51, 52],
       [60, 61, 62]])

In [56]:
# concatenate 数组进行连接

In [57]:
z.shape

(4, 3)

In [58]:
z = concatenate((x,y),axis =1)

In [59]:
# axis =1 代表的是改变的二维，可以集成1，改变二维，0改变一维

In [60]:
vstack((x,y)).shape

(4, 3)

In [61]:
vstack((x,y))

array([[ 0,  1,  2],
       [10, 11, 12],
       [50, 51, 52],
       [60, 61, 62]])

In [62]:
hstack((x,y))

array([[ 0,  1,  2, 50, 51, 52],
       [10, 11, 12, 60, 61, 62]])

In [63]:
dstack((x,y))

array([[[ 0, 50],
        [ 1, 51],
        [ 2, 52]],

       [[10, 60],
        [11, 61],
        [12, 62]]])

In [64]:
dstack((x,y)).shape

(2, 3, 2)

In [65]:
#faltten 数组

In [66]:
a = array([[0,1],[2,3]])

In [67]:
b = a.flatten()

In [68]:
b

array([0, 1, 2, 3])

In [69]:
# flatten返回的是数组的复制

In [70]:
b[0] =10

In [71]:
b

array([10,  1,  2,  3])

In [72]:
# 修改b，不影响a

In [73]:
a.flat

In [74]:
b = a.flat

In [75]:
b[0]

0

In [76]:
b[0] =10

In [77]:
b

In [78]:
a

array([[10,  1],
       [ 2,  3]])

In [82]:
mul = lambda x: x*x -1

In [83]:
mul(5)

24

In [84]:
a = array([[0,1],
           [2,3]])
b = a.ravel()

In [85]:
b

array([0, 1, 2, 3])

In [86]:
# atleast_xd函数

In [87]:
x = 1
atleast_1d(x)

array([1])

In [88]:
a = array([1,2,3])
b = atleast_2d(a)
b.shape

(1, 3)

In [89]:
b

array([[1, 2, 3]])

In [90]:
c = atleast_3d(b)

In [91]:
c

array([[[1],
        [2],
        [3]]])