In [1]:
#数组与字符串的转换

In [2]:
import numpy as np

In [3]:
a = np.array([[1,2],
           [3,4]], 
          dtype = np.uint8)

In [4]:
a.tostring

<function ndarray.tostring>

In [5]:
a

array([[1, 2],
       [3, 4]], dtype=uint8)

In [6]:
a.tostring(order='F')

b'\x01\x03\x02\x04'

In [7]:
s =  a.tostring()
a = np.fromstring(s,dtype=np.uint8)

/Users/zhangjianfeng/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  


In [8]:
a

array([1, 2, 3, 4], dtype=uint8)

In [10]:
a.reshape(2,2)

array([[1, 2],
       [3, 4]], dtype=uint8)