In [1]:
#一般函数操作

In [2]:
import numpy as np

In [3]:
# `hypot` 返回对应点 `(x,y)` 到原点的距离。

In [4]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [5]:
np.hypot(x,y)

array([4.12310563, 5.38516481, 6.70820393])

In [6]:
#正无穷
np.inf

inf

In [7]:
#负无穷
-np.inf

-inf

In [8]:
#非法值
np.nan

nan

In [9]:
#检查是否为无穷
np.isinf(1.0)

False

In [10]:
np.isinf(np.inf)

True

In [13]:
#非法值
np.array([0]) / 0.0

/Users/zhangjianfeng/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan])

In [14]:
a = np.arange(5.0)
b = a/0.0
b

/Users/zhangjianfeng/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  
/Users/zhangjianfeng/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan, inf, inf, inf, inf])

In [15]:
b == np.nan

array([False, False, False, False, False])

In [16]:
b

array([nan, inf, inf, inf, inf])

In [17]:
np.isnan(b)

array([ True, False, False, False, False])