In [1]:
#二元运算

In [2]:
import numpy as np

In [3]:
# 数组与标量相乘，相当于数组的每个元素乘以这个标量

In [6]:
a = np.arange(1,3,1)

In [7]:
a

array([1, 2])

In [8]:
a * 3

array([3, 6])

In [9]:
a = np.array([1,2])
b = np.array([3,4])
a * b

array([3, 8])

In [10]:
np.multiply(a,b)

array([3, 8])

运算|函数<
--- | --- 
`==` | `equal`
`!=` | `not_equal`
`>` | `greater`
`>=` | `greater_equal`
`<` | `less`
`<=` | `less_equal`
| `logical_and`
| `logical_or`
| `logical_xor`
| `logical_not`
`&` | `bitwise_and`
 | `bitwise_or`
`^` | `bitwise_xor`
`~` | `invert`
`>>` | `right_shift`
`<<` | `left_shift`

等于操作也是逐元素比较的：

In [11]:
a = np.array([[1,2,3,4],
              [2,3,4,5]])
b = np.array([[1,2,5,4],
              [1,3,4,5]])
a == b

array([[ True,  True, False,  True],
       [False,  True,  True,  True]])

这意味着，如果我们在条件中要判断两个数组是否一样时，不能直接使用

    if a == b:

而要使用：

    if all(a==b):

对于浮点数，由于存在精度问题，使用函数 `allclose` 会更好：

    if allclose(a,b):

`logical_and` 也是逐元素的 `and` 操作：

In [12]:
a = np.array([0,1,2])
b = np.array([0,10,0])

In [13]:
np.logical_and(a, b)

array([False,  True, False])

In [14]:
# 0 被认为是 False，非零则是 True。

In [ ]:
#比特操作：
a = np.array()