In [1]:
# choose 函数实现条件筛选

In [2]:
import numpy as np

In [3]:
control = np.array([[1,0,1],
                    [2,1,0],
                    [1,2,2]])

In [4]:
np.choose(control,[10,11,12])

array([[11, 10, 11],
       [12, 11, 10],
       [11, 12, 12]])

In [5]:
# 在上面的例子中，choose 将 0,1,2 对应的值映射为了 10, 11, 12，
# 这里的 0,1,2 表示对应的下标。
# 事实上， choose 不仅仅能接受下标参数，还可以接受下标所在的位置：

In [6]:
i0 = np.array([[0,1,2],
               [3,4,5],
               [6,7,8]])
i2 = np.array([[20,21,22],
               [23,24,25],
               [26,27,28]])
control = np.array([[1,0,1],
                    [2,1,0],
                    [1,2,2]])

np.choose(control, [i0, 10, i2])

array([[10,  1, 10],
       [23, 10,  5],
       [10, 27, 28]])

In [7]:
a = np.array([[ 0, 1, 2], 
              [10,11,12], 
              [20,21,22]])

a < 10

array([[ True,  True,  True],
       [False, False, False],
       [False, False, False]])

In [9]:
np.choose(a<10,(a,10))

array([[10, 10, 10],
       [10, 11, 12],
       [20, 21, 22]])

In [10]:
a = np.array([[ 0, 1, 2], 
              [10,11,12], 
              [20,21,22]])

lt = a < 10
gt = a > 15

choice = lt + 2 * gt
choice

array([[1, 1, 1],
       [0, 0, 0],
       [2, 2, 2]])