In [1]:
# 数组广播机制

In [2]:
import numpy as np

In [3]:
a = np.array([[ 0, 0, 0],
              [10,10,10],
              [20,20,20],
              [30,30,30]])
b = np.array([[ 0, 1, 2],
              [ 0, 1, 2],
              [ 0, 1, 2],
              [ 0, 1, 2]])
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [4]:
b = np.array([0,1,2])

In [5]:
b

array([0, 1, 2])

In [6]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [7]:
a = np.array([0,10,20,30])
a.shape = 4,1

In [8]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [9]:
b

array([0, 1, 2])

In [10]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [11]:
# 对于 Numpy 来说，维度匹配当且仅当：

# 维度相同,有一个的维度是1

In [12]:
a = np.array([0,10,20,30])
a.shape

(4,)

In [13]:
b.shape

(3,)

In [14]:
a+b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [15]:
a[:,np.newaxis] + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [16]:
a[:,np.newaxis] 

array([[ 0],
       [10],
       [20],
       [30]])

In [17]:
a

array([ 0, 10, 20, 30])

In [ ]:
x = np.linspace(-.5)