In [2]:
#数组读写

In [3]:
import numpy as np

In [4]:
data =[]

In [5]:
with open('myfile.txt') as f:
    for line in f:
        fileds = line.split()
        row_data = [float(x) for x in fileds]
        data.append(row_data)

In [6]:
data = np.array(data)

In [7]:
data

array([[2.1, 2.3, 3.2, 1.3, 3.1],
       [6.1, 3.1, 4.2, 2.3, 1.8]])

In [8]:
#都号分割的文件

In [9]:
data=np.loadtxt('myfile1.txt',delimiter=",")

In [10]:
data

array([[2.1, 2.3, 3.2, 1.3, 3.1],
       [6.1, 3.1, 4.2, 2.3, 1.8]])

In [11]:
# loadtxt 有很多可选参数，其中 delimiter 就是刚才用到的分隔符参数。
# skiprows 参数表示忽略开头的行数，可以用来读写含有标题的文本

In [12]:
np.loadtxt('myfile1.txt',delimiter=",",skiprows=1)

array([6.1, 3.1, 4.2, 2.3, 1.8])

In [13]:
#loadtxt的复杂操作
data = np.loadtxt('myfile2.txt', 
                  skiprows=1,         #忽略第一行
                  dtype=np.int,      #数组类型
                  delimiter=',',     #逗号分割
                  usecols=(0,1,2,4), #指定使用哪几列数据
                  comments='%'       #百分号为注释符
                 )
data

array([[   1,    1, 2000,   13],
       [   4,    1, 2000,   55]])

In [14]:
import datetime

In [15]:
def date_converter(s):
    return datetime.datetime.strptime(s,"%Y/%m/%d")

In [16]:
data = np.loadtxt('myfile3.txt',
                  dtype=np.object, #数据类型为对象
                  converters={0:date_converter,  #第一列使用自定义转换方法
                              1:float,           #第二第三使用浮点数转换
                              2:float})

data

TypeError: strptime() argument 1 must be str, not bytes

In [17]:
datetime.datetime.strptime('2012-08-25', "%Y-%m-%d")

datetime.datetime(2012, 8, 25, 0, 0)

In [18]:
# 将数组写入文件

In [19]:
data = np.array([[1,2],[3,4]])

In [20]:
np.savetxt('out.txt',data)

In [21]:
with open('out.txt') as f:
    for line in f:
        print(line)

1.000000000000000000e+00 2.000000000000000000e+00

3.000000000000000000e+00 4.000000000000000000e+00



In [22]:
data = np.array([[1,2], 
                 [3,4]])

np.savetxt('out.txt', data, fmt="%d") #保存为整数

In [23]:
with open('out.txt') as f:
    for line in f:
        print(line)

1 2

3 4



In [24]:
data = np.array([[1,2], 
                 [3,4]])

np.savetxt('out.txt', data, fmt="%.2f", delimiter=',') #保存为2位小数的浮点数，用逗号分隔

In [25]:
with open('out.txt') as f:
    for line in f:
        print(line)

1.00,2.00

3.00,4.00



In [26]:
import os
os.remove('out.txt')

In [27]:
a = np.array([[1.0,2.0], [3.0,4.0]])

fname = 'afile.npy'
np.save(fname, a)

In [28]:
aa = np.load(fname)
aa

array([[1., 2.],
       [3., 4.]])

In [29]:
import os
os.remove('afile.npy')

In [30]:
a = np.arange(10000.)

In [31]:
a

array([0.000e+00, 1.000e+00, 2.000e+00, ..., 9.997e+03, 9.998e+03,
       9.999e+03])

In [32]:
np.savetxt('a.txt', a)

In [33]:
import os
os.stat('a.txt').st_size

250000

In [34]:
np.save('a.npy', a)

In [35]:
os.stat('a.npy').st_size

80128

In [36]:
os.remove('a.npy')
os.remove('a.txt')

In [37]:
a = np.array([[1.0,2.0], 
              [3.0,4.0]])
b = np.arange(1000)

In [38]:
np.savez('data.npz', a=a, b=b)

In [39]:
!unzip -l data.npz

Archive:  data.npz
  Length      Date    Time    Name
---------  ---------- -----   ----
      160  01-01-1980 00:00   a.npy
     8128  01-01-1980 00:00   b.npy
---------                     -------
     8288                     2 files


In [40]:
data = np.load('data.npz')

In [41]:
data

In [42]:
data.keys()

['a', 'b']

In [43]:
data['a']

array([[1., 2.],
       [3., 4.]])

In [44]:
data['b'].shape

(1000,)

In [45]:
# 要先删除 data，否则删除时会报错
del data

os.remove('data.npz')

In [46]:
# 压缩文件

In [47]:
a = np.arange(20000.)

In [48]:
np.savez('a.npz', a=a)
os.stat('a.npz').st_size

160236

In [49]:
np.savez_compressed('a2.npz', a=a)
os.stat('a2.npz').st_size

26888

In [50]:
np.savez('a.npz', a=a)
os.stat('a.npz').st_size

160236

In [51]:
np.savez_compressed('a2.npz', a=a)
os.stat('a2.npz').st_size

26888

In [52]:
os.remove('a.npz')
os.remove('a2.npz')