In [1]:
#结构化数组

In [2]:
import numpy as np

In [3]:
a = np.array([1.0,2.0,3.0,4.0],np.float32)

In [4]:
a

array([1., 2., 3., 4.], dtype=float32)

In [5]:
a.view(np.complex64)

array([1.+2.j, 3.+4.j], dtype=complex64)

In [6]:
a

array([1., 2., 3., 4.], dtype=float32)

In [7]:
my_dtype = np.dtype([('mass', 'float32'), ('vol', 'float32')])

In [8]:
my_dtype

dtype([('mass', '<f4'), ('vol', '<f4')])

In [9]:
a.view(my_dtype)

array([(1., 2.), (3., 4.)], dtype=[('mass', '<f4'), ('vol', '<f4')])

In [10]:
# f4 表示四字节浮点数，< 表示小字节序

In [11]:
my_data = np.array([(1,1), (1,2), (2,1), (1,3)], my_dtype)

In [12]:
my_data

array([(1., 1.), (1., 2.), (2., 1.), (1., 3.)],
      dtype=[('mass', '<f4'), ('vol', '<f4')])

In [13]:
my_data[0]

(1., 1.)

In [14]:
my_data[0]['vol']

1.0

In [15]:
my_data['mass']

array([1., 1., 2., 1.], dtype=float32)

In [16]:
my_data.sort(order=('vol', 'mass'))
my_data

array([(1., 1.), (2., 1.), (1., 2.), (1., 3.)],
      dtype=[('mass', '<f4'), ('vol', '<f4')])

In [17]:
person_dtype = np.dtype([('name', 'S10'), ('age', 'int'), ('weight', 'float')])

In [18]:
person_dtype.itemsize

26

In [19]:
people = np.empty((3,4), person_dtype)

In [20]:
people['name'] = [['Brad', 'Jane', 'John', 'Fred'],
                  ['Henry', 'George', 'Brain', 'Amy'],
                  ['Ron', 'Susan', 'Jennife', 'Jill']]

In [21]:
people['age'] = [[33, 25, 47, 54],
                 [29, 61, 32, 27],
                 [19, 33, 18, 54]]

In [22]:
people['weight'] = [[135., 105., 255., 140.],
                    [154., 202., 137., 187.],
                    [188., 135., 88., 145.]]

In [23]:
people

array([[(b'Brad', 33, 135.), (b'Jane', 25, 105.), (b'John', 47, 255.),
        (b'Fred', 54, 140.)],
       [(b'Henry', 29, 154.), (b'George', 61, 202.),
        (b'Brain', 32, 137.), (b'Amy', 27, 187.)],
       [(b'Ron', 19, 188.), (b'Susan', 33, 135.), (b'Jennife', 18,  88.),
        (b'Jill', 54, 145.)]],
      dtype=[('name', 'S10'), ('age', '<i8'), ('weight', '<f8')])

In [25]:
people[-1,-1]

(b'Jill', 54, 145.)

In [26]:
%%writefile people.txt
name age weight
amy 11 38.2
john 10 40.3
bill 12 21.2

Writing people.txt


In [27]:
with open('people.txt') as f:
    print(f)

<_io.TextIOWrapper name='people.txt' mode='r' encoding='UTF-8'>


In [28]:
person_dtype = np.dtype([('name', 'S10'), ('age', 'int'), ('weight', 'float')])

people = np.loadtxt('people.txt', 
                    skiprows=1,
                    dtype=person_dtype)

people

array([(b'amy', 11, 38.2), (b'john', 10, 40.3), (b'bill', 12, 21.2)],
      dtype=[('name', 'S10'), ('age', '<i8'), ('weight', '<f8')])

In [29]:
people['name']

array([b'amy', b'john', b'bill'], dtype='|S10')

In [30]:
import os
os.remove('people.txt')

In [31]:
%%writefile wood.csv
item,material,number
100,oak,33
110,maple,14
120,oak,7
145,birch,3

Writing wood.csv


In [32]:
tree_to_int = dict(oak = 1,
                   maple=2,
                   birch=3)

def convert(s):
    return tree_to_int.get(s, 0)

In [33]:
data = np.genfromtxt('wood.csv',
                     delimiter=',', # 逗号分隔
                     dtype=np.int, # 数据类型
                     names=True,   # 从第一行读入域名
                     converters={1:convert}
                    )

In [34]:
data

array([(100, 0, 33), (110, 0, 14), (120, 0,  7), (145, 0,  3)],
      dtype=[('item', '<i8'), ('material', '<i8'), ('number', '<i8')])

In [35]:
# 使用 genfromtxt 载入数据，可以自动从第一行读入属性名称：

In [36]:
data['material']

array([0, 0, 0, 0])

In [37]:
os.remove('wood.csv')

In [39]:
particle_dtype = np.dtype([('position', [('x', 'float'), 
                                          ('y', 'float')]),
                                           ('mass', 'float')
                                          ])

In [40]:
particle_dtype

dtype([('position', [('x', '<f8'), ('y', '<f8')]), ('mass', '<f8')])

In [41]:
%%writefile data.txt
2.0 3.0 42.0
2.1 4.3 32.5
1.2 4.6 32.3
4.5 -6.4 23.3

Writing data.txt
